# Generated by Django 4.2.6 on 2023-10-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=120)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
